#!/usr/bin/env node
// Regenerates src/app/core/version.ts from package.json's "version" field --
// single source of truth for the header's version badge (app.ts), avoids a
// second place to remember to bump on release. Runs via the "postinstall"
// npm hook (package.json) so it's always fresh before any build/serve/test,
// same lifecycle-hook pattern this repo already uses for husky ("prepare").
//
// .mjs (not .js) so this runs as ESM regardless of package.json's "type"
// field -- no "type": "module" needed project-wide just for this script.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');
const pkg = JSON.parse(readFileSync(join(rootDir, 'package.json'), 'utf-8'));

const output = `// AUTO-GENERATED by scripts/generate-version.mjs (postinstall) -- do not edit by hand.
export const APP_VERSION = '${pkg.version}';
`;

const outDir = join(rootDir, 'src', 'app', 'core');
// mkdirSync (not an assumed-existing src/) -- Dockerfile's build stage runs
// `npm ci` (this script's postinstall trigger) before `COPY . .`, so src/
// doesn't exist on disk yet at that point. writeFileSync alone would fail
// with ENOENT there even though the script itself is present -- hit live.
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'version.ts'), output);
console.log(`Generated src/app/core/version.ts -> ${pkg.version}`);
