# -----------------------------------------------------------------------------------------------
# This workflow built the project on every pull request and on every manual trigger.
# This workflow is used in pull request as a required check.
# -----------------------------------------------------------------------------------------------
name: "CI - Lint, Test & Build"
run-name: CI - Run Lint, Test & Build

on:
  workflow_dispatch:
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v7

      - name: "Setup Node and install deps"
        uses: alderichoarau/gha-setup-node@v2

      - name: "Check lint"
        run: npm run lint

      - name: "Run test"
        run: npm run test:coverage

      - name: "Build project"
        run: npm run build
